import type { Metadata } from "next";
import { Inter } from "next/font/google"; // 1. Hapus import Geist
import "./globals.css";
import { Providers } from "../components/Providers";

// 2. Hapus definisi geistSans dan geistMono

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // 3. Gunakan hanya variabel Inter di sini
        className={`${inter.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}