import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../components/Providers";
import { Sidebar } from "../components/Sidebar"; // Import the sidebar
import { Navbar } from "../components/Navbar"; // Import the navbar
import { Toaster } from "../components/ui/toaster";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Your Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const defaultChannelId = process.env.YOUTUBE_CHANNEL_ID || '';

  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.className} antialiased font-sans bg-white`}>
        <Providers initialChannelId={defaultChannelId}>
          {/* Main Flex Container */}
          <div className="flex h-screen overflow-hidden">

            {/* Left Sidebar */}
            <Sidebar />

            {/* Right Content Area */}
            <main className="flex-1 bg-gray-50 overflow-y-auto">
              {/* Navbar */}
              <Navbar />

              {/* Page Content */}
              <div className="p-6">
                {children}
              </div>
            </main>

          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}